pipeline {
    agent any
    environment {
      registry = "gcr.io/jenkins-360510/python-fahrenheit-docker-0815"
      dockerimage = ''
    }
    stages {
      stage('Build Docker image') {
        steps {
          script {
            dockerImage = docker.build registry + ":$BUILD_NUMBER"
          }
        }
      }
      stage('Push Docker Image to GCR') {
        steps {
          script {
            withDockerRegistry(credentialsId: 'gcr:jenkins-360510', url: 'https://gcr.io/')
            {
              dockerImage.push()
            }
          }
        }
      }
    }
}
